#
# Konfigurace specifická pro vývojové prostředí.
#

title: Vývojový Portál o datech České republiky

# Odkazy na registrační formuláře.
app_registration_form: https://forms.cloud.microsoft/e/JX4WGmJ6dS
suggestion_form: https://forms.cloud.microsoft/e/zafBRy6R9G

# Nesmí končit znakem "/".
ofn_origin: https://ofn-develop.dia.gov.cz
